apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rYz-DevOps/rYz-DevOps.git
    targetRevision: argocd
    directory:
      recurse: true
    path: argocd/deployments/nginx/
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
