apiVersion: batch/v1
kind: Job
metadata:
  name: create-mysql-table
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: arm64v8/mysql:latest
          command: ["sh", "-c", "mysql -h $MYSQL_HOST -u $MYSQL_USER -p $MYSQL_PASSWORD $MYSQL_DATABASE -e 'CREATE TABLE $TABLE_NAME (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY (id));'"]
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: TABLE_NAME
              value: new
          volumeMounts:
            - name: mysql-client-certs
              mountPath: /etc/mysql-client/certs
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: mysql-client-certs
      imagePullSecrets:
        - name: mysql
