apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31110
    port: 6000
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31211
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: test-app
  sessionAffinity: None
  type: LoadBalancer
